version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: mysql-container-ecomtracker
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ecomtracker
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: springboot-app-ecomtracker
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/ecomtracker?allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL: "true"
      API_SECURITY_TOKEN_SECRET: 1234567
      STRIPE_API_KEY: sk_test_51Nldf0Jhg2zvdVu1i7UYANTwW5AvtxUqH2H1enzFu1iqvol6sb0ryeM9SsKYLq4oEJpaOSsP7E4gjqFNawjh5wCL001JGo1nUU
      STRIPE_WEBHOOK_SECRET: whsec_17d7870013fe8c584b87aa1c46a1df5eed15d760d8a86d56aafd85b0d30d09c5
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network

  stripe-cli:
    image: stripe/stripe-cli
    container_name: stripe-cli-ecomtracker
    command: "listen --api-key sk_test_51Nldf0Jhg2zvdVu1i7UYANTwW5AvtxUqH2H1enzFu1iqvol6sb0ryeM9SsKYLq4oEJpaOSsP7E4gjqFNawjh5wCL001JGo1nUU --forward-to app:8080/webhook/stripe"
    networks:
      - app-network
    depends_on:
      - app

volumes:
  db_data:

networks:
  app-network: