version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: mysql-container-ecomtracker
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ecomtracker
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 30s
      timeout: 10s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: springboot-app-ecomtracker
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/ecomtracker
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL: "true"
      API_SECURITY_TOKEN_SECRET: 1234567
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
